apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: shared-services
  name: longhorn-pvc-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

apiVersion: v1
kind: Pod
metadata:
  name: test-pod-pvc
  namespace: shared-services
spec:
  containers:
    - name: test-pod-pvc
      image: busybox
      command:
      - sleep
      args:
      - "infinity"
      volumeMounts:
      - mountPath: "/mnt/pv"
        name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: longhorn-pvc-test
